site_name: SAEs for Sentence-BERT
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/banner.png

nav:
  - Quick start: index.md
  - Introduction to the project: introduction.md
  - SAE models: saes.md
  - Activation Store: activationstore.md
  - Training: training.md
  - Tutorials:
      - How to use SAEs: tutorials/tutorial_use.md
      - Keyword extraction: tutorials/keywords.md
      - Feature analysis: tutorials/feature_analysis.md
  - Results: results.md
  - References: references.md