site_name: SAEs for Sentence-BERT
theme:
  name: material
  logo: assets/logo.png

nav:
  - Quick start: index.md
  - Introduction to the project: introduction.md
  - SAE models: saes.md
  - Activation Store: activationstore.md
  - Training: training.md
  - Feature analysis:
      - Keyword extraction: interpretability/keywords.md
      - Visualization: interpretability/visualization.md
  - Results: results.md